// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/19/2024, 10:23:14 PM
const configMerger = require("/Users/gaetano.vallarelli/Sites/personal/pdl/valfleur/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/gaetano.vallarelli/Sites/personal/pdl/valfleur/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gaetano.vallarelli/Sites/personal/pdl/valfleur/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gaetano.vallarelli/Sites/personal/pdl/valfleur/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gaetano.vallarelli/Sites/personal/pdl/valfleur/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gaetano.vallarelli/Sites/personal/pdl/valfleur/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gaetano.vallarelli/Sites/personal/pdl/valfleur/plugins/**/*.{js,ts,mjs}","/Users/gaetano.vallarelli/Sites/personal/pdl/valfleur/composables/**/*.{js,ts,mjs}","/Users/gaetano.vallarelli/Sites/personal/pdl/valfleur/utils/**/*.{js,ts,mjs}","/Users/gaetano.vallarelli/Sites/personal/pdl/valfleur/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/gaetano.vallarelli/Sites/personal/pdl/valfleur/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/gaetano.vallarelli/Sites/personal/pdl/valfleur/app.config.{js,ts,mjs}"] } }));

module.exports = config
